@startuml
class Persona {
  - nombre: String  
  - edad: int  
  + getNombre(): String 
  + setNombre(String): void 
}
Persona <|-- Estudiante
class Estudiante {
  - matricula: String  
  + estudiar(): void 
}
Estudiante --  "0..*" Curso
class Profesor {
  - salario: double  
  + enseñar(): void 
}
Profesor --  "1..*" Curso
class Curso {
  - codigo: String  
  - nombre: String  
  + agregarEstudiante(Estudiante): void 
}
Curso *--  "1..*" Material
class Material {
  - titulo: String  
  - autor: String  
}
class Animal {
  - nombre: String  
  + hacerSonido(): void {abstract}
}
Animal <|-- Perro
Animal <|-- Gato
class Perro {
  - raza: String  
  + hacerSonido(): void 
}
class Gato {
  - color: String  
  + hacerSonido(): void 
}
interface Serializable {
  + serializar(): String
}
@enduml