@startuml Diagram
actor/ "Cliente" as actorCliente <<usuario>>
actor "Administrador" as actorAdmin <<gestor>>
usecase/ ("Comprar Producto") as useCaseCompra  <<transaccion>>
usecase/ ("Gestionar Inventario") as useCaseInventario  <<gestion>>
package "E-Commerce" as packageEcom {
usecase/ ("Añadir al Carrito") as useCaseCarrito 
actor/ "Sistema de Pagos" as actorPago <<servicio>>
package "Pago" as packagePago {
usecase/ ("Procesar Pago") as useCaseProcesarPago 
actor/ "Banco" as actorBanco <<entidad>>
}
}
actorCliente -right-> useCaseCompra:"Realiza"
useCaseCarrito .> useCaseCompra: extends
packageEcom -left-> packagePago:"Relaciona con"
@enduml